# Generated by Django 4.2.27 on 2026-02-01 09:58

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('briefings', '0001_initial'),
        ('documents', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='briefing',
            name='attachments',
            field=models.ManyToManyField(blank=True, related_name='attached_to_briefings', to='documents.document'),
        ),
        migrations.AddField(
            model_name='briefing',
            name='client',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='briefings', to='core.client'),
        ),
        migrations.AddField(
            model_name='briefing',
            name='created_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_briefings', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='briefing',
            name='household',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='briefings', to='core.household'),
        ),
        migrations.AddField(
            model_name='briefing',
            name='template',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='briefings', to='briefings.briefingtemplate'),
        ),
        migrations.AddIndex(
            model_name='notification',
            index=models.Index(fields=['user', 'is_read'], name='briefings_n_user_id_1a9dad_idx'),
        ),
        migrations.AddIndex(
            model_name='briefing',
            index=models.Index(fields=['household', 'status'], name='briefings_b_househo_8252e1_idx'),
        ),
        migrations.AddIndex(
            model_name='briefing',
            index=models.Index(fields=['client', 'status'], name='briefings_b_client__a3b1a8_idx'),
        ),
        migrations.AddIndex(
            model_name='briefing',
            index=models.Index(fields=['status', 'scheduled_for'], name='briefings_b_status_b0ac7c_idx'),
        ),
    ]
