# Generated by Django 4.2.27 on 2026-02-01 09:31

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AuditQueryLog',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('query_type', models.CharField(max_length=50)),
                ('query_params', models.JSONField(default=dict)),
                ('result_count', models.PositiveIntegerField(default=0)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-timestamp'],
            },
        ),
        migrations.CreateModel(
            name='AuditEvent',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('timestamp', models.DateTimeField(db_index=True, default=django.utils.timezone.now, editable=False)),
                ('event_type', models.CharField(choices=[('auth.login', 'User Login'), ('auth.logout', 'User Logout'), ('auth.login_failed', 'Login Failed'), ('auth.mfa_challenge', 'MFA Challenge'), ('auth.password_change', 'Password Change'), ('auth.password_reset', 'Password Reset'), ('data.view', 'Data Viewed'), ('data.download', 'Data Downloaded'), ('data.export', 'Data Exported'), ('data.create', 'Data Created'), ('data.update', 'Data Updated'), ('data.delete', 'Data Deleted'), ('doc.upload', 'Document Uploaded'), ('doc.view', 'Document Viewed'), ('doc.download', 'Document Downloaded'), ('doc.share', 'Document Shared'), ('doc.delete', 'Document Deleted'), ('comm.briefing_sent', 'Briefing Sent'), ('comm.meeting_pack', 'Meeting Pack Generated'), ('comm.report_sent', 'Report Sent'), ('admin.user_create', 'User Created'), ('admin.user_update', 'User Updated'), ('admin.user_deactivate', 'User Deactivated'), ('admin.permission_change', 'Permission Changed'), ('admin.settings_change', 'Settings Changed'), ('sys.integration_sync', 'Integration Sync'), ('sys.integration_error', 'Integration Error'), ('sys.backup', 'System Backup'), ('sys.error', 'System Error')], db_index=True, max_length=50)),
                ('severity', models.CharField(choices=[('debug', 'Debug'), ('info', 'Info'), ('warning', 'Warning'), ('error', 'Error'), ('critical', 'Critical')], default='info', max_length=10)),
                ('user_email', models.EmailField(blank=True, max_length=254)),
                ('target_type', models.CharField(blank=True, db_index=True, max_length=100)),
                ('target_id', models.CharField(blank=True, db_index=True, max_length=100)),
                ('target_repr', models.CharField(blank=True, max_length=255)),
                ('client_id', models.UUIDField(blank=True, db_index=True, null=True)),
                ('household_id', models.UUIDField(blank=True, db_index=True, null=True)),
                ('description', models.TextField(blank=True)),
                ('data', models.JSONField(blank=True, default=dict)),
                ('old_values', models.JSONField(blank=True, default=dict)),
                ('new_values', models.JSONField(blank=True, default=dict)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('user_agent', models.TextField(blank=True)),
                ('request_id', models.CharField(blank=True, max_length=100)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='audit_events', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-timestamp'],
                'indexes': [models.Index(fields=['event_type', 'timestamp'], name='audit_audit_event_t_a63184_idx'), models.Index(fields=['user', 'timestamp'], name='audit_audit_user_id_314539_idx'), models.Index(fields=['client_id', 'timestamp'], name='audit_audit_client__a82af0_idx'), models.Index(fields=['target_type', 'target_id'], name='audit_audit_target__59bbff_idx')],
            },
        ),
    ]
